@baseUrl = http://localhost:3000

### Read all films
GET {{baseUrl}}/films

### Read all films with minimum-duration of 140min
GET {{baseUrl}}/films/?minimum-duration=130

### Try to read films with wrong minimum-duration
GET {{baseUrl}}/films/?minimum-duration=0

### Read film with ID == 1
GET {{baseUrl}}/films/1

### Read film which does not exist
GET {{baseUrl}}/films/500

### Create a film
POST {{baseUrl}}/films/
Content-Type: application/json

{
    "title":"Star Wars: The Phantom Menace (Episode I)",
    "duration": 136,
    "director": "George Lucas",
    "budget": 115,
    "imageUrl":"https://upload.wikimedia.org/wikipedia/en/4/40/Star_Wars_Phantom_Menace_poster.jpg"
}

### Try to create a film with a parameter missing
POST {{baseUrl}}/films/
Content-Type: application/json

{
    "title":" ",
    "duration": 136,
    "budget": 115,
    "imageUrl":"https://upload.wikimedia.org/wikipedia/en/4/40/Star_Wars_Phantom_Menace_poster.jpg"
}

### Try to create a film with an empty string or string with whitespaces only
POST {{baseUrl}}/films/
Content-Type: application/json

{
    "title":" ",
    "duration": 136,
    "director": "George Lucas",
    "budget": 115,
    "imageUrl":"https://upload.wikimedia.org/wikipedia/en/4/40/Star_Wars_Phantom_Menace_poster.jpg"
}

### Try to create a film with a wrong budget (string instead of number)
POST {{baseUrl}}/films/
Content-Type: application/json

{
    "title":"Star Wars: The Phantom Menace (Episode I)",
    "duration": 136,
    "director": "George Lucas",
    "budget": "115",
    "imageUrl":"https://upload.wikimedia.org/wikipedia/en/4/40/Star_Wars_Phantom_Menace_poster.jpg"
}

### Challenge of ex1.4 : Try to create a film with an unexpected parameter
POST {{baseUrl}}/films/
Content-Type: application/json

{
    "title":"Star Wars: The Phantom Menace (Episode I)",
    "duration": 136,
    "director": "George Lucas",
    "budget": 115,
    "imageUrl":"https://upload.wikimedia.org/wikipedia/en/4/40/Star_Wars_Phantom_Menace_poster.jpg",
    "unexpected": "unexpected"
}

### Try to create a film which already exists (same title and director)
POST {{baseUrl}}/films/
Content-Type: application/json

{
    "title":"Star Wars: The Phantom Menace (Episode I)",
    "duration": 136,
    "director": "George Lucas",
    "budget": 115,
    "imageUrl":"https://upload.wikimedia.org/wikipedia/en/4/40/Star_Wars_Phantom_Menace_poster.jpg"
}

############################################## DELETE ########################################

### Delete a film with ID == 1
DELETE  {{baseUrl}}/films/1

### Try to delete a film that does not exists
DELETE  {{baseUrl}}/films/66

############################################ PATCH ##########################################

### Update a film with ID == 1
PATCH {{baseUrl}}/films/1
Content-Type: application/json

{
    "title":"Star Wars: The Phantom Menace (Episode I)",
    "duration": 156,
    "director": "George Lucas",
    "budget": 115,
    "imageUrl":"https://upload.wikimedia.org/wikipedia/en/4/40/Star_Wars_Phantom_Menace_poster.jpg"
}

### Try to update a film that does not exists
PATCH {{baseUrl}}/films/999
Content-Type: application/json

  {
    "title": "Shang-Chi and the Legend of the Ten Rings (Director's Cut)",
    "duration": 162,
    "description":
      "Shang-Chi, the master of unarmed weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization. (Director's Cut)",
    "budget": 160
  }

### Try to update a film with invalid parameters (blackspace)
PATCH {{baseUrl}}/films/1
Content-Type: application/json

  {
    "title": " ",
    "description":
      "Shang-Chi, the master of unarmed weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization. (Director's Cut)",
    "budget": 160
  }

### Try to update a film with invalid parameters (duration < 0)
PATCH {{baseUrl}}/films/1
Content-Type: application/json

  {
    "title": "Shang-Chi and the Legend of the Ten Rings (Director's Cut)",
    "duration": -162,
    "description":
      "Shang-Chi, the master of unarmed weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization. (Director's Cut)",
    "budget": 160
  }
  

######################################## PUT ###############################################

### Update a film
PUT {{baseUrl}}/films/1
Content-Type: application/json

{
    "title":"Star Wars: The Phantom Menace (Episode I)",
    "duration": 136,
    "director": "George Lucas",
    "budget": 115,
    "imageUrl":"https://upload.wikimedia.org/wikipedia/en/4/40/Star_Wars_Phantom_Menace_poster.jpg"
}

### Create a film that does not exists by uptdating it
PUT {{baseUrl}}/films/999
Content-Type: application/json

{
    "title":"Star Wars: The Phantom Menace (Episode I) (Remake)",
    "duration": 196,
    "director": "Ridley Scott",
    "budget": 365,
    "imageUrl":"https://upload.wikimedia.org/wikipedia/en/4/40/Star_Wars_Phantom_Menace_poster.jpg"
}

### Try to Update a film without a mandatory params (director missing)
PUT {{baseUrl}}/films/1
Content-Type: application/json

{
    "title":"Star Wars: The Phantom Menace (Episode I)",
    "duration": 136,
    "budget": 115,
    "imageUrl":"https://upload.wikimedia.org/wikipedia/en/4/40/Star_Wars_Phantom_Menace_poster.jpg"
}

### Try to Update/Create a film with a invalid param (budget < 0)
PUT {{baseUrl}}/films/1
Content-Type: application/json

{
    "title":"Star Wars: The Phantom Menace (Episode I)",
    "duration": 136,
    "director": "George Lucas",
    "budget": -115,
    "imageUrl":"https://upload.wikimedia.org/wikipedia/en/4/40/Star_Wars_Phantom_Menace_poster.jpg"
}