@baseUrl = http://localhost:3000

######### NORMAL OPERATION  ###########
### Read all books with File variable

GET {{baseUrl}}/books


### Read pizza identified by 2
GET {{baseUrl}}/books/2


### Create a pizza by using the admin account
#### First login as the admin
##### Define a request variable nammed admin :
# @name admin
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}

### Read all books with File variable
GET {{baseUrl}}/books
Authorization: {{admin.response.body.token}}


### Read pizza identified by 2
GET {{baseUrl}}/books/1
Authorization: {{admin.response.body.token}}

