### Read all films
GET http://localhost:3000/films

### Read all films with File variable
@baseUrl = http://localhost:3000
GET {{baseUrl}}/films

### Read all films with a minimum duration of 120 min
GET {{baseUrl}}/films?minimum-duration=130

# C: Forget to add a case with the wrong minimum duration. (Request below)

### Try to read films with wrong minimum-duration
GET {{baseUrl}}/films/?minimum-duration=0

### Read a single film with the id 3
GET {{baseUrl}}/films/3

# C: Forget to add a request with a Film that doesn't exist. (Request below)

### Create film 1
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title": "Blade Runner 2049",
    "director": "Denis Villeneuve",
    "duration": 164,
    "budget": 150,
    "description": "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    "imageUrl": "https://upload.wikimedia.org/wikipedia/en/8/81/Blade_Runner_2049_logo.png"
}

### Create film 2 (without optionnal properties)
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title": "Your Name.",
    "director": "Makoto Shinkai",
    "duration": 106,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/en/0/0b/Your_Name_poster.png"
}

### Try to create a film  with a duration < 0 (KO)
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title": "The Room",
    "director": "Tommy Wiseau",
    "duration": -99,
    "budget": 6,
    "description": "Johnny is a successful bank executive who lives quietly in a San Francisco townhouse with his fiancée, Lisa.",
    "imageUrl": "https://upload.wikimedia.org/wikipedia/en/e/e1/TheRoomMovie.jpg"
}

### Try to create a film without director (KO)
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title": "Arrival",
    "duration": 116,
    "budget": 47,
    "description": "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.",
    "imageUrl": "https://upload.wikimedia.org/wikipedia/en/d/df/Arrival_%282016_film%29.jpg"
}

# C: Forget to add a case with "to create a film with an empty string or string with whitespaces only"

##################################### C: MISSING REQUESTS ######################################
### Try to read films with wrong minimum-duration
GET {{baseUrl}}/films/?minimum-duration=0

### Read film which does not exist
GET {{baseUrl}}/films/500

### Try to create a film with an empty string or string with whitespaces only
POST {{baseUrl}}/films/
Content-Type: application/json

{
    "title":" ",
    "duration": 136,
    "director": "George Lucas",
    "budget": 115,
    "imageUrl":"https://upload.wikimedia.org/wikipedia/en/4/40/Star_Wars_Phantom_Menace_poster.jpg"
}


